fail_fast: true

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: check-added-large-files
          - id: check-toml
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-merge-conflict
          - id: debug-statements
          - id: fix-byte-order-marker

    - repo: local
      hooks:
          - id: local-ruff-check
            name: ruff check
            entry: uv run ruff check --force-exclude --fix --exit-non-zero-on-fix
            require_serial: true
            language: unsupported
            types: [python]

          - id: local-ty
            name: ty (type check)
            entry: uv run ty check
            pass_filenames: false
            language: system
            types: [python]
